### ISSUE TITLE
http://co.cc/ is a valid URL

### ISSUE THREAD

**Issue by juliensobrier** [tal/URL#1]
http://co.cc/ is not handled correctly. The problem is the special case in the method "initialize", line 100.

**Comment by tal** [comment]
Thanks for reporting. I'll check it out right away.

**Comment by juliensobrier** [comment]
I'm trying to do a merge request for this change: https://github.com/juliensobrier/URL/commit/8ed2dde2c87c8350daf92648a04c453e587d566e

**Comment by tal** [comment]
Released new version of gem to rubygems.org 0.3.2
